#!/bin/bash
set -euxo pipefail


# 1. Install Build Dependencies
echo "Installing build dependencies..."
sudo yum groupinstall -y "Development Tools" # Installs gcc, make, autoconf, automake, etc.
sudo yum install -y openssl-devel libevent-devel sqlite-devel wget

# 2. Download Coturn Source Code
echo "Downloading Coturn version ${coturn_version_tf_var}..."
cd /usr/src
sudo wget "https://github.com/coturn/coturn/archive/refs/tags/${coturn_version_tf_var}.tar.gz" -O "coturn-${coturn_version_tf_var}.tar.gz"
sudo tar -zxvf "coturn-${coturn_version_tf_var}.tar.gz"

# 3. Compile and Install Coturn
echo "Building and installing Coturn from source..."
cd "coturn-${coturn_version_tf_var}"
sudo ./configure --prefix=/usr/local
sudo make -j$(nproc) # Use all available processors for faster build
sudo make install
sudo ldconfig # Refresh shared library cache

# 4. Create Coturn Configuration File
CONFIG_PATH="/usr/local/etc/turnserver.conf"
echo "Creating Coturn configuration file at $${CONFIG_PATH}..."

# Retry fetching IP addresses up to 5 times with a 10-second delay
# Using IMDSv2, which requires fetching a token first
IMDS_TOKEN=""
TOKEN_RETRY_COUNT=0
MAX_TOKEN_RETRIES=3 # Fewer retries for token, as it should be available quickly

echo "Attempting to fetch IMDSv2 token..."
while [ -z "$${IMDS_TOKEN}" ] && [ "$TOKEN_RETRY_COUNT" -lt "$MAX_TOKEN_RETRIES" ]; do
  IMDS_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" || true)
  if [ -z "$${IMDS_TOKEN}" ]; then
    TOKEN_RETRY_COUNT=$((TOKEN_RETRY_COUNT + 1))
    if [ "$TOKEN_RETRY_COUNT" -lt "$MAX_TOKEN_RETRIES" ]; then
      echo "Failed to fetch IMDSv2 token. Retrying in 5 seconds..."
      sleep 5
    else
      echo "FATAL: Failed to fetch IMDSv2 token after $MAX_TOKEN_RETRIES attempts. Cannot retrieve instance metadata."
      # exit 1 # Or handle this more gracefully depending on requirements
      # For now, we allow proceeding, variables will be empty, coturn might fail or bind to 0.0.0.0
    fi
  else
    echo "Fetched IMDSv2 token."
  fi
done

RETRY_COUNT=0
MAX_RETRIES=5
RETRY_DELAY=10
MY_IP=""
MY_PUBLIC_IP=""

if [ -n "$${IMDS_TOKEN}" ]; then
  while [ -z "$${MY_IP:-}" ] && [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
    echo "Attempting to fetch local IP using IMDSv2 (Attempt: $((RETRY_COUNT + 1)))..."
    MY_IP=$(curl -s -H "X-aws-ec2-metadata-token: $${IMDS_TOKEN}" --connect-timeout 5 http://169.254.169.254/latest/meta-data/local-ipv4 || true)
    if [ -z "$${MY_IP:-}" ]; then
      RETRY_COUNT=$((RETRY_COUNT + 1))
      if [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; then
        echo "Failed to fetch local IP. Retrying in $RETRY_DELAY seconds..."
        sleep $RETRY_DELAY
      else
        echo "Failed to fetch local IP after $MAX_RETRIES attempts. Proceeding with empty value."
      fi
    else
      echo "Fetched local IP: $MY_IP"
    fi
  done

  RETRY_COUNT=0 # Reset for public IP
  while [ -z "$${MY_PUBLIC_IP:-}" ] && [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
    echo "Attempting to fetch public IP using IMDSv2 (Attempt: $((RETRY_COUNT + 1)))..."
    MY_PUBLIC_IP=$(curl -s -H "X-aws-ec2-metadata-token: $${IMDS_TOKEN}" --connect-timeout 5 http://169.254.169.254/latest/meta-data/public-ipv4 || true)
    if [ -z "$${MY_PUBLIC_IP:-}" ]; then
      RETRY_COUNT=$((RETRY_COUNT + 1))
      if [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; then
        echo "Failed to fetch public IP. Retrying in $RETRY_DELAY seconds..."
        sleep $RETRY_DELAY
      else
        echo "Failed to fetch public IP after $MAX_RETRIES attempts. Proceeding with empty value."
      fi
    else
      echo "Fetched public IP: $MY_PUBLIC_IP"
    fi
  done
else
  echo "WARNING: Could not obtain IMDSv2 token. IP addresses will likely be empty."
fi

# If still empty after retries, set a placeholder or let coturn decide (e.g. by leaving them empty)
# For now, we'll proceed, and coturn might bind to 0.0.0.0 if they are empty.
# MY_IP (shell variable, was using :- for default)
# MY_PUBLIC_IP (shell variable, was using :- for default)

cat << EOF | sudo tee "$${CONFIG_PATH}"
# Coturn configuration file generated by user-data script
listening-port=3478
# tls-listening-port=5349 # Disabled as we are not using TLS/DTLS for this test server

# Disable TLS and DTLS listeners as we don't have certs for this temp server
no-tls
no-dtls

listening-ip=$MY_IP
relay-ip=$MY_IP 
external-ip=$MY_PUBLIC_IP

realm="${turn_realm}"
server-name="${turn_realm}"

# user setting removed for open TURN server
# Added for open TURN server
no-auth

# Use fingerprint for STUN messages
fingerprint

# Log to stdout for systemd/journald
log-file=stdout

# Verbosity is handled by systemd logging and absence of -v on command line
# no-verbose # Removed, default is not verbose

# Standard relay port range
min-port=49152
max-port=65535

# Other common options for security/stability:
# lt-cred-mech # Commented out because no-auth is enabled
# stale-nonce # Commented out because no-auth is enabled
# no-loopback-peers # Removed, default is to disallow loopback peers
no-multicast-peers

# Optional: Specify a PID file (useful for some management scripts, though systemd handles main process)
# pidfile="/var/run/turnserver.pid"

EOF

# 5. Create systemd service file for Coturn
SYSTEMD_SERVICE_PATH="/etc/systemd/system/coturn.service"
echo "Creating systemd service file at $${SYSTEMD_SERVICE_PATH}..."

cat << EOF_SERVICE | sudo tee "$${SYSTEMD_SERVICE_PATH}"
[Unit]
Description=Coturn TURN Server
After=network.target
Documentation=man:turnserver(1) man:turnadmin(1) man:turnutils(1)

[Service]
Type=simple
ExecStart=/usr/local/bin/turnserver -c $${CONFIG_PATH}
Restart=always
RestartSec=3
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF_SERVICE

# 6. Reload systemd, enable and start Coturn service
echo "Reloading systemd, enabling and starting Coturn service..."
sudo systemctl daemon-reload
sudo systemctl enable coturn
sudo systemctl start coturn

echo "Coturn setup from source complete."

# Check coturn status (optional, for debugging during startup)
# sudo systemctl status coturn
# journalctl -u coturn -f 