//! FreeRDP FFI bindings
//!
//! This module contains the raw FFI bindings generated by bindgen,
//! plus safe wrapper types.
//!
//! Supports both FreeRDP 2.x and 3.x APIs through compatibility aliases.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]
#![allow(unused_imports)]

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/freerdp_bindings.rs"));

// Re-export common types with better names
pub use self::freerdp as FreeRdpInstance;
pub use self::rdpContext as RdpContext;
pub use self::rdpGdi as RdpGdi;
pub use self::rdpInput as RdpInput;
pub use self::rdpSettings as RdpSettings;
pub use self::rdpUpdate as RdpUpdate;

// ============================================================================
// FreeRDP 3.x Settings Key Compatibility Layer
// ============================================================================
// FreeRDP 3 uses typed settings keys (e.g., FreeRDP_Settings_Keys_String_FreeRDP_ServerHostname)
// This module provides simplified aliases for common settings.

/// String setting keys (for use with freerdp_settings_set_string)
pub mod settings_string {
    use super::*;
    pub const SERVER_HOSTNAME: FreeRDP_Settings_Keys_String =
        FreeRDP_Settings_Keys_String_FreeRDP_ServerHostname;
    pub const USERNAME: FreeRDP_Settings_Keys_String =
        FreeRDP_Settings_Keys_String_FreeRDP_Username;
    pub const PASSWORD: FreeRDP_Settings_Keys_String =
        FreeRDP_Settings_Keys_String_FreeRDP_Password;
    pub const DOMAIN: FreeRDP_Settings_Keys_String = FreeRDP_Settings_Keys_String_FreeRDP_Domain;
}

/// UInt32 setting keys (for use with freerdp_settings_set_uint32)
pub mod settings_uint32 {
    use super::*;
    pub const SERVER_PORT: FreeRDP_Settings_Keys_UInt32 =
        FreeRDP_Settings_Keys_UInt32_FreeRDP_ServerPort;
    pub const DESKTOP_WIDTH: FreeRDP_Settings_Keys_UInt32 =
        FreeRDP_Settings_Keys_UInt32_FreeRDP_DesktopWidth;
    pub const DESKTOP_HEIGHT: FreeRDP_Settings_Keys_UInt32 =
        FreeRDP_Settings_Keys_UInt32_FreeRDP_DesktopHeight;
    pub const COLOR_DEPTH: FreeRDP_Settings_Keys_UInt32 =
        FreeRDP_Settings_Keys_UInt32_FreeRDP_ColorDepth;
    pub const PERFORMANCE_FLAGS: FreeRDP_Settings_Keys_UInt32 =
        FreeRDP_Settings_Keys_UInt32_FreeRDP_PerformanceFlags;
    pub const CONNECTION_TYPE: FreeRDP_Settings_Keys_UInt32 =
        FreeRDP_Settings_Keys_UInt32_FreeRDP_ConnectionType;
}

/// Boolean setting keys (for use with freerdp_settings_set_bool)
pub mod settings_bool {
    use super::*;
    pub const NLA_SECURITY: FreeRDP_Settings_Keys_Bool =
        FreeRDP_Settings_Keys_Bool_FreeRDP_NlaSecurity;
    pub const TLS_SECURITY: FreeRDP_Settings_Keys_Bool =
        FreeRDP_Settings_Keys_Bool_FreeRDP_TlsSecurity;
    pub const RDP_SECURITY: FreeRDP_Settings_Keys_Bool =
        FreeRDP_Settings_Keys_Bool_FreeRDP_UseRdpSecurityLayer;
    pub const EXT_SECURITY: FreeRDP_Settings_Keys_Bool =
        FreeRDP_Settings_Keys_Bool_FreeRDP_ExtSecurity;
    pub const IGNORE_CERTIFICATE: FreeRDP_Settings_Keys_Bool =
        FreeRDP_Settings_Keys_Bool_FreeRDP_IgnoreCertificate;
    pub const SOFTWARE_GDI: FreeRDP_Settings_Keys_Bool =
        FreeRDP_Settings_Keys_Bool_FreeRDP_SoftwareGdi;
    pub const DISABLE_WALLPAPER: FreeRDP_Settings_Keys_Bool =
        FreeRDP_Settings_Keys_Bool_FreeRDP_DisableWallpaper;
    pub const DISABLE_FULL_WINDOW_DRAG: FreeRDP_Settings_Keys_Bool =
        FreeRDP_Settings_Keys_Bool_FreeRDP_DisableFullWindowDrag;
    pub const DISABLE_MENU_ANIMS: FreeRDP_Settings_Keys_Bool =
        FreeRDP_Settings_Keys_Bool_FreeRDP_DisableMenuAnims;
    pub const DISABLE_THEMES: FreeRDP_Settings_Keys_Bool =
        FreeRDP_Settings_Keys_Bool_FreeRDP_DisableThemes;
    pub const OLD_LICENSE_BEHAVIOUR: FreeRDP_Settings_Keys_Bool =
        FreeRDP_Settings_Keys_Bool_FreeRDP_OldLicenseBehaviour;
}
